version: '3.4'

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: 'oteldemo'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      # <Port exposed> : <MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql  
      - "./database-scripts/init.sql:/docker-entrypoint-initdb.d/1.sql"
    networks:
      - my-networks


  otel-demo-api1:
    build:
      context: .
      dockerfile: "./src/Otel.Demo.Api1/Dockerfile"
    depends_on:
      - db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80      
    ports:
      - "8080:80"    
    networks:
      - my-networks
  
networks:
  my-networks:
    driver: bridge
# Names our volume
volumes:
  my-db: